"""empty message

Revision ID: 310ae119cc7f
Revises: 8fa16c51ac53
Create Date: 2017-08-09 15:07:16.807292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '310ae119cc7f'
down_revision = '8fa16c51ac53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('identity_name_key', 'identity', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('identity_name_key', 'identity', ['name'])
    # ### end Alembic commands ###
